### ISSUE TITLE
Script doesn't assume https

### ISSUE THREAD

**Issue by TheFiZi** [ziirish/zerocli#2]
Ran this:

```
[user@localhost zero-cli]$ echo "This is the internet" | ./zerocli.sh -S paste.somewhere.com
No JSON object could be decoded
./zerocli.sh: line 150: [: -ne: unary operator expected
No JSON object could be decoded
No JSON object could be decoded
Your data have been successfully pasted
url: paste.somewhere.com?#vX5Sre6Gi0SRWMaity0mnrz5jNNlPPkHnVP3X5vidMg=
delete url: paste.somewhere.com?pasteid=&deletetoken=
```

This obviously didn't work.

Re-running the command and putting "https://" in front of the server name resulted in success.

Maybe the script can just assume it should append https:// in front of the -S value if it's not there? and force someone to override if they want to use http:// since we're all about security :)

**Comment by ckorn** [comment]
What is a working command line actually?

This did not work:

```
korn@pc:/tmp/zerocli$ LANG=C ./zerocli.sh -S https://0bin.net -f compact.sh -p
No JSON object could be decoded                                    
./zerocli.sh: line 150: [: -ne: unary operator expected
No JSON object could be decoded
No JSON object could be decoded
Your data have been successfully pasted
url: https://0bin.net?#xgHXhIXzwT12+HIiZm8I7NE0mf89z+7t/o4wjr8A6XM=
delete url: https://0bin.net?pasteid=&deletetoken=
```

**Comment by TheFiZi** [comment]
I ran

```
echo "This is the internet" | ./zerocli.sh -S https://paste.xxx.xxx
```

and was successful. I'm not using a self-signed SSL certificate. Are you?

**Comment by ziirish** [comment]
Thanks, I'll have a look at that.

There are actually two problems here.

1) I don't check the server URL passed to the script
2) my json parsing method is a little bit crappy

**Comment by ziirish** [comment]
Hi again.

Finally I won't force https since you can now configure your server using a configuration file for global settings or via the command line.
Curl manpage says "If  you  specify  URL without protocol:// prefix, curl will attempt to guess what protocol you might want. It will then default to HTTP but try other protocols based on often-used host name prefixes." so I'll let curl handle it.

Anyway, I made the code more robust and print out more explicit errors.

Here is an example:

ziirish@carbon:~$ zerocli -S domain.tld/tmp
azerty

Encrypting data... [done]
Got a redirection 302 to 'https://another.tld/'
retrying...
OK server returned code 200
Your data have been successfully pasted
url: domain.tld/tmp/?6569253212792a3d#YBakaf3DiWvn0m91ha1w75IXH2MU4bY3Kz3PE9062co=
delete url: domain.tld/tmp/?pasteid=6569253212792a3d&deletetoken=41fc42612413be136ff157c5032a9af9081b12e2
ziirish@carbon:~$ zerocli -S 0bin.net
azerty

Encrypting data... [done]
Error: server returned 405
